services:
  - type: static
    name: md-zakir-hussain-portfolio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
